"""update

Revision ID: 0ad839e83248
Revises: 2e583eb158b4
Create Date: 2025-08-01 09:25:06.270896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad839e83248'
down_revision = '2e583eb158b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('permissions_role_fkey'), type_='foreignkey')
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('permissions_role_fkey'), 'roles', ['role'], ['id'])

    # ### end Alembic commands ###
