"""add other tables

Revision ID: 536817608c85
Revises: e9cef9c259ef
Create Date: 2025-06-29 17:20:49.874461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536817608c85'
down_revision = 'e9cef9c259ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PaymentMethod',
    sa.Column('authentication', sa.Text(), nullable=True),
    sa.Column('payment_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_name')
    )
    op.create_table('attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('brand-categorys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('key', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('brandcategory', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brandcategory'], ['brand-categorys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cart'], ['carts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provinces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('country', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('key', sa.String(length=200), nullable=True),
    sa.Column('province', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['province'], ['provinces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('brand_name', sa.String(length=300), nullable=True),
    sa.Column('about', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['brand_name'], ['brands.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Specailproducts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('product', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('city', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=999), nullable=True),
    sa.Column('postal_code', sa.String(length=999), nullable=True),
    sa.Column('User', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['User'], ['users.id'], ),
    sa.ForeignKeyConstraint(['city'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_table('cart_products',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('amount', sa.Integer(), nullable=True),
    # sa.Column('product_id', sa.Integer(), nullable=True),
    # sa.Column('cart_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    # sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    op.create_table('category_and_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoryid', sa.Integer(), nullable=True),
    sa.Column('productid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoryid'], ['category.id'], ),
    sa.ForeignKeyConstraint(['productid'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('attribute_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_attributes')
    op.drop_table('category_and_product')
    op.drop_table('cart_products')
    op.drop_table('address_user')
    op.drop_table('Specailproducts')
    op.drop_table('products')
    op.drop_table('city')
    op.drop_table('provinces')
    op.drop_table('orders')
    op.drop_table('brands')
    op.drop_table('coupons')
    op.drop_table('country')
    op.drop_table('category')
    op.drop_table('carts')
    op.drop_table('brand-categorys')
    op.drop_table('attributes')
    op.drop_table('PaymentMethod')
    # ### end Alembic commands ###
