"""remove detail

Revision ID: e9cef9c259ef
Revises: f54e03a798d4
Create Date: 2025-06-29 16:47:50.870665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9cef9c259ef'
down_revision = 'f54e03a798d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
